### ISSUE TITLE
Version 0.7.x fails to compile in Webpack

### ISSUE THREAD

**Issue by luke3butler** [feathersjs/hooks#100]
### TL;DR

Version 0.7.x fails to compile (Webpack). Version 0.6.5 compiles successfully.

I tried 0.6.5 after finding issue #98 

### Steps to reproduce

I have a generic VueJS 2 install created with the Vue CLI (using Webpack)...

### Expected behavior
Should build/run successfully

### Actual behavior
Fails to compile with
```
 ERROR  Failed to compile with 1 error                                                                                                                         6:14:31 PM

 error  in ./node_modules/@feathersjs/hooks/esm/base.js

Module parse failed: Unexpected token (55:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     middleware(middleware) {
>         this._middleware = middleware?.length ? middleware : null;
|         return this;
|     }

 @ ./node_modules/@feathersjs/hooks/esm/index.js 1:0-40 5:0-26 5:0-26 13:24-35 31:27-38
 @ ./node_modules/@feathersjs/feathers/lib/dependencies.js
 @ ./node_modules/@feathersjs/feathers/lib/index.js
 @ ./src/utils/feathers-api.js
 @ ./src/utils/index.js
 @ ./src/plugins/http.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://<local-ip>:3000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

### System configuration

**Module versions**:

packages.json
```json
  "dependencies": {
    "@feathersjs/authentication-client": "^5.0.0-pre.17",
    "@feathersjs/feathers": "^5.0.0-pre.17",
    "@feathersjs/socketio-client": "^5.0.0-pre.17",
    "feathers-hooks-common": "^5.0.6",
    "socket.io-client": "^4.4.1",
    ...
  }
```

feathers.js file
```js
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'
import auth from '@feathersjs/authentication-client'
import io from 'socket.io-client'

const socket = io('http://localhost:3030', { transports: ['websocket'] })

// This variable name becomes the alias for this server.
export const api = feathers()
  .configure(socketio(socket))
  .configure(auth({ storage: window.localStorage }));
```

**Comment by daffl** [comment]
Did you set up Webpack [as shown here](https://dove.docs.feathersjs.com/api/client.html#webpack)?

**Comment by luke3butler** [comment]
@daffl after digging further in, I figured out a solution that lets the application compile. 

Simply excluding isn't enough here. Standard Vue projects use ` vue.config.js` for configuration rather than dealing with Webpack directly.

Although I was successful in modifying the Webpack configuration (through either `chainWebpack` or `configureWebpack` options), the error persisted.

***Solution***
```js
module.exports = {
  transpileDependencies: ["@feathersjs/hooks"]
};
```
Should I transpile the entire `@feathersjs` namespace as well? Taking the approach of "if it ain't broke don't fix it", but I'd also like to create a documentation PR for this somewhere.

**Comment by luke3butler** [comment]
Added a documentation update PR [here](https://github.com/feathersjs/docs/pull/1561).
