### ISSUE TITLE
Allow to change the order of middleware

### ISSUE THREAD

**Issue by daffl** [feathersjs/hooks#11]
This is a follow-up for https://github.com/feathersjs/feathers/pull/1590 to discuss options for allowing to change the order of middleware. Registering new middleware is currently possible using `registerMiddleware`:

```js
const { hooks, registerMiddleware, getMiddleware } = require('@feathersjs/hooks');

// Hooks can be used with a function like this:
const sayHello = hooks(async name => {
  return `Hello ${name}!`;
}, [
  logRuntime,
  validateName
]);

registerMiddleware(sayHello, [
  otherHook
]);
```

However, it currently appends `otherHook` to the existing chain. One improvement possible would be to add a `setMiddleware` that allows to replace all middleware in combination with `getMiddleware` like this:

```js
const { hooks, setMiddleware, getMiddleware } = require('@feathersjs/hooks');

// Hooks can be used with a function like this:
const sayHello = hooks(async name => {
  return `Hello ${name}!`;
}, [
  logRuntime,
  validateName
]);

setMiddleware(sayHello, [
  otherHook,
  ...getMiddleware(sayHello)
]);
```

Now `otherHook` would run first and your middleware chains are still explicitly defined.

**Comment by daffl** [comment]
Additionally it is also possible to customize where middleware is coming from using the [`collect` option](https://github.com/feathersjs/hooks#options).

**Comment by bertho-zero** [comment]
```js
setMiddleware(sayHello, registeredHooks => [
  otherHook,
  ...registeredHooks
]);
```

like `setState` from React ?
