### ISSUE TITLE
integrate it to existing feathers app

### ISSUE THREAD

**Issue by noor-tg** [feathersjs/hooks#20]
how to integrate this package to existing feathers app ?

**Comment by averri** [comment]
This is a very relevant question, we hope to get some information soon.

**Comment by daffl** [comment]
You can use it in your app already right now as documented. For the core integration, follow the https://github.com/feathersjs/feathers/pull/1798 PR and other linked ones.

**Comment by averri** [comment]
Hi @daffl, I haven't found anything there explaining how to use the new `hooks` in an app with Feathersjs v4. I'm particularly interested in this new model because it will make it easier for adding cross cutting concerns like logging. The actual hooks in Feathersjs v4, although it's very clean, it's difficult to implement a cross cutting concerns that spans the entire client request (vide https://github.com/feathersjs/feathers/issues/1881).

**Comment by averri** [comment]
I think it deserves a brief demo about how to integrate it with existing Feathersjs v4. It should show the 'old' Feathersjs v4 hooks style and the new style for a side-by-side comparison.

**Comment by daffl** [comment]
That will be the next step for v5. This release specifically focussed on being usable standalone without anything else Feathers related. You can attach them to any object including a service:

```js
const { hooks } = require('@feathersjs/hooks');
const app = feathers();

const logRuntime = async (context, next) => {
  const start = new Date().getTime();

  await next();

  const end = new Date().getTime();

  console.log(`Function '${context.method || '[no name]'}' returned '${context.result}' after ${end - start}ms`);
}

hooks(app.service('messages'), {
  create: [ logRuntime ]
});
```

This can be accomplished for all services using [app.mixins](https://docs.feathersjs.com/api/application.html#mixins). Note that required properties (like `app` and `service` currently have to be added manually by [customizing the context](https://github.com/feathersjs/hooks#customizing-and-returning-the-context)).

**Comment by averri** [comment]
@daffl, thanks for informing that. The v5 is a great evolution of the framework.

**Comment by daffl** [comment]
This has now been done in the Feathers v5.0.0-beta.0 prerelease where the new hooks are a first class citizen. See the [migration guide](https://dove.docs.feathersjs.com/guides/migrating.html) for how to test it.
