### ISSUE TITLE
API usage improvements

### ISSUE THREAD

**Issue by daffl** [feathersjs/hooks#22]
The current API still feels a little verbose. I'd really like to offer something that is chainable, offering all the current functionality but a little more concise:

```js
const sayHi = hooks(name => `Hi ${name}`, [ hook1 ]).params('name').defaults({
  name: 'Dave'
});
```

This would still work on objects:

```js
const o = {
  sayHi(name) { return `Hi ${name}` }
}

hooks(o, {
  sayHi: hooks([ hook1 ]).params('name').defaults({
    name: 'Dave'
  })
});
```

**Comment by bertho-zero** [comment]
https://github.com/feathersjs/hooks/pull/23
