### ISSUE TITLE
Brings webpack as dependency and many other due to that

### ISSUE THREAD

**Issue by bitflower** [feathersjs/hooks#26]
Hi,

I just prepared a PR to our master that introduces `@feathersjs/hooks`. I was a little shocked by the many changes my `package-lock.json` showed. I have dozens of `@webassemblyjs/...` dependencies added:
<img width="1001" alt="Bildschirmfoto 2020-02-20 um 22 57 46" src="https://user-images.githubusercontent.com/6666636/74982687-e1b52880-5434-11ea-9155-ca1f0658e918.png">

I have the feeling that this is introduced by the `webpack` dependency that comes with this lib here:
<img width="1003" alt="Bildschirmfoto 2020-02-20 um 22 57 36" src="https://user-images.githubusercontent.com/6666636/74982732-f5608f00-5434-11ea-9385-8726dcd28337.png">

<img width="908" alt="Bildschirmfoto 2020-02-20 um 23 02 01" src="https://user-images.githubusercontent.com/6666636/74982785-07dac880-5435-11ea-9c05-1ebc04dd8e2d.png">

I don't use `webpack` in my project - I use `rollup` so my question is: Does your lib need this? Can't this be a devDep?

Thanks,
Matt

**Comment by bitflower** [comment]
Would making it a devDep help at all?

**Comment by bitflower** [comment]
I think I might just completely have missunderstood the purpose of the lock file too.

**Comment by daffl** [comment]
The `package-lock.json` just makes sure that if you clone down the repository you get the right dependency versions (dev or not).

**Comment by bertho-zero** [comment]
You have installed version `0.2.0` of `@feathersjs/hooks` rather than latest or `0.4.0-alpha.0`.

**Comment by bitflower** [comment]
That solved it @bertho-zero ! The file looks much cleaner now with `0.3.1`. Thanks for the feedback @daffl

**Comment by bitflower** [comment]
And sorry for the noise....
