### ISSUE TITLE
Is it possible to remove a hook?

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs/hooks#53]
For example, I have the following: 

```js
const { hooks } = require('@feathersjs/hooks');

const logRuntime = async (context, next) => {
	// ...
}

class Hello {
  async sayHi (name) {
    return `Hi ${name}`
  }
}

hooks(Hello, {
  sayHi: [
    logRuntime
  ]
});
```

How do I remove the `logRuntime` hook?

**Comment by bertho-zero** [comment]
There is no official way to remove a hook.

The easiest in this case is to run the hook conditionally with https://hooks-common.feathersjs.com/hooks.html#iff

**Comment by mikeconley12** [comment]
Thank you for the answer
