### ISSUE TITLE
Wrong method name in context.method

### ISSUE THREAD

**Issue by mikeconley12** [feathersjs/hooks#60]
### Steps to reproduce

Please use [this example](https://repl.it/repls/AwfulNaiveTheories#index.js). In this example, I called the `create()` method, but `context.method` gives me `find` instead of `create`.

### Expected behavior
I expected to get the following output from the example:

```
context.method create
```

### Actual behavior
I get the following output from the example:

```
context.method find
```

### System configuration

**Module versions**:

```
@feathersjs/hooks: 0.5.0
```

**NodeJS version**: v12.18.3

**Operating System**: Linux

**Comment by bertho-zero** [comment]
I see it on master but it is fixed with https://github.com/feathersjs/hooks/pull/57

**Comment by bertho-zero** [comment]
On your REPL I notice that the error changes depending on the order of line 29 to 32.

# :thinking:

**Comment by bertho-zero** [comment]
`@feathersjs/hooks` directly modify your middleware array:

1. https://github.com/feathersjs/hooks/blob/d1a388338253038c282e2b427517d7224b39fa08/packages/hooks/src/base.ts#L34

2. https://github.com/feathersjs/hooks/blob/d1a388338253038c282e2b427517d7224b39fa08/packages/hooks/src/hooks.ts#L95

**Comment by mikeconley12** [comment]
> I see it on master but it is fixed with #57

Good, so it would be great if https://github.com/feathersjs/hooks/pull/57 was merged.

**Comment by daffl** [comment]
Closed now via https://github.com/feathersjs/hooks/pull/57

**Comment by mikeconley12** [comment]
Thanks!

**Comment by mikeconley12** [comment]
@daffl could you please tell me when you plan to publish this fix to NPM?
