### ISSUE TITLE
function.length is lost

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/hooks#76]
`function.length` is lost, and I see an error calling `hooks` without hooks argument.

```js
const { hooks } = require('@feathersjs/hooks');

const emptyHook = async (context, next) => next();

// Hooks can be used with a function like this:
const sayHello = async name => {
  return `Hello ${name}!`;
};

const sayHello2 = hooks(async name => {
  return `Hello ${name}!`;
});

const sayHello3 = hooks(async name => {
  return `Hello ${name}!`;
}, []);

const sayHello4 = hooks(async name => {
  return `Hello ${name}!`;
}, [emptyHook]);

(async () => {
  console.log(sayHello.length); // 1
  console.log(sayHello2.length); // 3, should be 1
  console.log(sayHello3.length); // 0, should be 1
  console.log(sayHello4.length); // 0, should be 1
  
  console.log(await sayHello('Bertho'));
  // console.log(await sayHello2('Bertho'));
  // Throw an error: TypeError: manager.parent is not a function
  //  at Object.setManager
  console.log(await sayHello3('Bertho'));
  console.log(await sayHello4('Bertho'));
})();
```

**Comment by bertho-zero** [comment]
The same may be happening with `function.name`, I haven't checked.

**Comment by daffl** [comment]
Hm, so according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) the property is not writeable but configurable. I tested this and it looked like it worked (but not sure if that applies to all engines):

```js
function blabla (a, b, c) {}
Object.defineProperty(blabla, 'length', { value: 5 })
console.log(blabla.length);
```

**Comment by bertho-zero** [comment]
![image](https://user-images.githubusercontent.com/8525267/113900890-968fdd80-97ce-11eb-963c-d37363581495.png)

The configurable seems newer than the function.length, and still not supported on IE.

This redefinition of length and name must be in a try catch in my opinion.

**Comment by bertho-zero** [comment]
![image](https://user-images.githubusercontent.com/8525267/113983930-d1375b80-984a-11eb-9e05-03d594b497fd.png)

As expected, it's broken in IE.
