### ISSUE TITLE
Error: Could not dynamically require "./base.js".

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/hooks#96]
While trying to bundle with Vite, I encounter the following error:

```
[mf:err] Error: Could not dynamically require "./base.js". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
    at commonjsRequire (/Users/user/Sites/cf-feathers-2/dist/index.mjs:73:9)
    at /Users/user/Sites/cf-feathers-2/node_modules/@feathersjs/hooks/umd/index.js:22:23
```

This problem occurs even when just using @feathersjs/feathers, and not manually importing @feathersjs/hooks anywhere in user code.

I've tried fixing the issue using the `dynamicRequireTargets` and `ignoreDynamicRequires` options, and while they do fix this specific problem, they mess up the ability for modules in @feathersjs/feathers to properly import @feathersjs/hooks.

**Comment by marshallswain** [comment]
The solution to this was to use the `resolve.alias` feature of Vite/RollupJS.  I pointed `@feathersjs/hooks` to the esm build instead of the umd build.  My new config with the `resole.alias` in place looks like this:

```js
// vite.config.js
const path = require('path')
const isProduction = !process.env.CF_LOCAL_BUILD

module.exports = {
  resolve: {
    alias: {
      '@feathersjs/hooks': 'node_modules/@feathersjs/hooks/esm/index.js'
    }
  },
  build: {
    sourcemap: isProduction ? false : 'inline',
    minify: isProduction,
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      formats: ['es'],
      fileName: 'index',
    }
  }
}
```

**Comment by daffl** [comment]
This should work out of the box without any module bundler configuration no?

**Comment by marshallswain** [comment]
It does in Deno and possibly with mjs in Node.  I’m using Vite for easy
TS support and better common js compatibility.

On November 21, 2021, GitHub ***@***.***> wrote:
> This should work out of the box without any module bundler
> configuration no?
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/feathersjs/hooks/issues/96#issuecomment-974858761>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAA7OWIAFKBLAA2LXQ5224LUNETBFANCNFSM5IPCDS6A>.
