### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by rybkowskigrzegorz** [feathersjs/hooks#98]
Hi 👋 
I'm trying to compile ts library with `hooks` package, but keep getting error issues which point to `umd` module. 

```
WARNING in ../../node_modules/@feathersjs/hooks/umd/utils.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@feathersjs/hooks/umd/base.js
 @ ../../node_modules/@feathersjs/hooks/umd/index.js
 @ ./src/plugins/ImageColorConverter/ImageColorConverter.ts 55:14-42
 @ ./src/index.ts 6:28-88
```
I have several issues like this. This is my webpack.config file that I'm using

```
const path = require('path')

module.exports = {
  entry: './src/index.ts',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'index.js',
    library: {
      name: 'productDesigner',
      type: 'umd',
    },
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  externals: {
    react: 'react',
    lodash: 'lodash',
  },
}
```

I'm using in in one submodule of this library.

**Module versions**
`"@feathersjs/hooks": "0.7.2"`

**NodeJS version**:
`v16.13.0`

**Operating System**:
macOS Monterey

**Browser Version**:
Chrome Version 97.0.4692.99 (Official Build) (arm64)

**Module Loader**:
`"webpack": "5.68.0",`

**Comment by daffl** [comment]
We have been seeing the same when trying to upgrade Feathers. I created a [follow-up issue in the build tool](https://github.com/denoland/dnt/issues/113) that we are using. For now you might want to stick with version [v0.6.5](https://github.com/feathersjs/hooks/releases/tag/v0.6.5) which shouldn't have that problem and has mostly the same functionality.

**Comment by daffl** [comment]
Just verified that this has been fixed in the latest version I just published :smile:
